### ISSUE TITLE
[Python missing modules]No module named maas - No module named apiclient

### ISSUE THREAD

**Issue by Jgerardopine** [maas/python-libmaas#82]
Hi,

 I have been trying to run python-maas from a remote server to reach the Rack-Controller through the API so I can get some information, but nothing seems to work. I tried the examples under the documentation and every time I find that I have missing modules:

Trying to run the example in docs- index-An example directly in Pythoon prompt
>>> from maas.client import login
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'maas'

Trying to run an example from stackoverflow
>>>Traceback (most recent call last):
  File "./maas-py-client.py", line 8, in <module>
    from apiclient import maas_client
ImportError: No module named 'apiclient'

Tryng to run as an script (obviously same error as the first one - tried this one after creating a new VM):
>>>(amc) ubuntu@ubuntu:~$ ./maas-test-python.py
Traceback (most recent call last):
  File "./maas-test-python.py", line 3, in <module>
    from maas.client import login
ImportError: No module named 'maas'

I have installed as per the instructions:
$ virtualenv --python=python3.5 amc && source amc/bin/activate
$ pip install git+https://github.com/maas/python-libmaas.git
$ maas --help

I get the maas client working. But I guess that since there are some problems in the python libraries I can't get logged in with specifique api keys. Just as Anonymous and of course I can't access any command. This are the errors:

(amc) ubuntu@ubuntu:~$ maas profiles list
┌──────────────┬───────────────────────┬─────┐
│ Profile name │            URL                         │ Anonymous?      │ Default?│
├──────────────┼───────────────────────┼─────┤
│ nexius-test  │ http://<IP>/MAAS/api/2.0/ │ Yes                      │ ✓         │
└──────────────┴──_____──────────────────┴─────┘

`maasprofiles login <profile> http://<IP>:5240/MAAS/api/2.0/ <apikey>
Password:`
`Error: coroutine raised StopIteration`

Since I am with the anonymous user I can't get into any command:
`maas list-users`
`Error: 'NoneType' object has no attribute 'read'`

I am using ubuntu 16.04.
 I am not sure if I am missing something (most likely) or if there is other branch I should be using?  Because I tried in 3 different VMs and it is not working. The same missing modules. 
Can you help me?

**Comment by allenap** [comment]
Hi Jgerardopine.

The first half is, I think, because you're using the "old" client for MAAS. This is packaged in Ubuntu as _maas-cli_. The new _python-libmaas_ is currently only available via [PyPI](https://pypi.python.org/pypi/python-libmaas) or installed directly from source. In time it will be packaged for Ubuntu and replace _maas-cli_, but that's a little way off.

The second (`StopIteration`) problem is a weird bug that we noticed only a few days ago. We think this is related to the use of an IP address instead of a hostname when connecting to MAAS. Would you mind trying again using a hostname?

There's a workaround if that doesn't work. Obtain, by hand, an API token from the user preferences page in the UI (`http://$address:$port/MAAS/account/prefs/`) and put it into the following command:

```console
$ maas profiles add nexius-test http://$address:$port/MAAS/ $api_token
```

I am working actively to fix the `login` bug. It needs a server-side fix too, and that's what I'm working on first. What version of the MAAS server are you using?

Gavin.

**Comment by Jgerardopine** [comment]
Hi Gavin,

  I am currently using maas 2.1.3+bzr5573-0ubuntu1~16.04.1 500.

  1) As you said the workaround worked perfectly. It only works with
hostnames though but I finally can use maas commands in the remote server.
  2) As for the maas-lib you were right. For some reason I didn't realised
about the example I was using. I found an example of last year and I
thought the syntax was not that different.


Best regards,

Jose Gerardo Pineda

**Comment by allenap** [comment]
Excellent, I'm glad it's up and running now. Please file bugs for any other problems you encounter. Thanks!
